volumes:
  el_data:
  cl_data:
  prometheus_data:


networks:
  shared_network:
    external: true

services:
  reth:
    build:
      context: ../../../services/reth
      dockerfile: Dockerfile
      args:
        - VERSION=v1.8.3
    command: [ "/app/entrypoint.sh" ]
    container_name: "${EL_DNS}"
    restart: unless-stopped
    volumes:
      - el_data:/data
      - ./secrets/jwtsecret:/config/jwtsecret
    ports:
      - "${EL_RPC_PORT}:${EL_RPC_PORT}" # json rpc
      - "${EL_WS_PORT}:${EL_WS_PORT}" # ws rpc
      - "${EL_METRICS_PORT}:${EL_METRICS_PORT}" # prometheus at host 7001
      - "${EL_P2P_PORT}:${EL_P2P_PORT}" # p2p
      - "${EL_P2P_PORT}:${EL_P2P_PORT}/udp" # p2p udp
    networks:
      - shared_network
    env_file:
      - .env

  beacon-node:
    build:
      context: ../../../services/lighthouse
      dockerfile: Dockerfile
      args:
        - VERSION=v8.0.0-rc.2
    command: [ "/app/beacon-node-entrypoint.sh" ]
    container_name: "${CL_BEACON_NODE_DNS}"
    restart: unless-stopped
    volumes:
      - cl_data:/data
      - ./secrets/jwtsecret:/config/jwtsecret
    ports:
      - "${BEACON_NODE_METRICS_PORT}:${BEACON_NODE_METRICS_PORT}" # prometheus at host
      - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}" # p2p
      - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}/udp" # p2p
      - "${BEACON_NODE_GRPC_PORT}:${BEACON_NODE_GRPC_PORT}" # grpc gateway port
      - "${BEACON_NODE_RPC_PORT}:${BEACON_NODE_RPC_PORT}" # rpc port
    networks:
      - shared_network
    env_file:
      - .env

  prometheus:
    build:
      context: ../../../services/prometheus
      dockerfile: Dockerfile
    command: [ "/app/prometheus-entrypoint.sh" ]
    container_name: "${PROMETHEUS_DNS}"
    restart: unless-stopped
    volumes:
      - prometheus_data:/data
      - ./prometheus-template.yml:/app/prometheus-template.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - shared_network
    env_file:
      - .env
