volumes:
  geth_data:
    name: holesky_geth_data
  prysm_data:
    name: holesky_prysm_data
  prometheus_data:
    name: holesky_prometheus_data

services:
  holesky-el-geth:
    build:
      context: ../../../services/geth
      dockerfile: Dockerfile
    container_name: holesky-el-geth
    command: [ "/app/geth-entrypoint.sh" ]
    volumes:
      - geth_data:/data
      - type: bind
        source: ../../../services/shared/jwtsecret
        target: /config/jwtsecret
    ports:
      - "${EL_RPC_PORT}:${EL_RPC_PORT}" # json rpc
      - "${EL_WS_PORT}:${EL_WS_PORT}" # ws rpc
      - "${EL_METRICS_PORT}:${EL_METRICS_PORT}" # prometheus at host 7001
      - "${EL_P2P_PORT}:${EL_P2P_PORT}" # p2p
      - "${EL_P2P_PORT}:${EL_P2P_PORT}/udp" # p2p udp
    env_file:
      - .env

  holesky-cl-prysm-beacon-node:
    build:
      context: ../../../services/prysm
      dockerfile: Dockerfile
    container_name: holesky-cl-prysm-beacon-node
    command: [ "/app/beacon-node-entrypoint.sh" ]
    volumes:
      - prysm_data:/data
      - type: bind
        source: ../../../services/shared/jwtsecret
        target: /config/jwtsecret
    ports:
      - "${BEACON_NODE_METRICS_PORT}:${BEACON_NODE_METRICS_PORT}" # prometheus at host
      - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}" # p2p
      - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}/udp" # p2p
      - "${BEACON_NODE_GRPC_PORT}:${BEACON_NODE_GRPC_PORT}" # grpc gateway port
      - "${BEACON_NODE_RPC_PORT}:${BEACON_NODE_RPC_PORT}" # rpc port
    env_file:
      - .env

  holesky-cl-prysm-validator:
    build:
      context: ../../../services/prysm
      dockerfile: Dockerfile
    container_name: holesky-cl-prysm-validator
    command: [ "/app/validator-entrypoint.sh" ]
    depends_on:
      holesky-cl-prysm-validator-account-import:
        condition: service_completed_successfully
    volumes:
      - prysm_data:/data
      - ./validator_keys:/app/validator_keys # set your own key path
      - ./passwd/wallet-passwd:/config/wallet-passwd # remember to set your passwd
    ports:
      - "${VALIDATOR_METRICS_PORT}:${VALIDATOR_METRICS_PORT}"
    env_file:
      - .env

  # importing accounts for validator
  holesky-cl-prysm-validator-account-import:
    build:
      context: ../../../services/prysm
      dockerfile: Dockerfile
    container_name: holesky-cl-prysm-validator-account-import
    command: [ "/app/validator-import-accounts.sh" ]
    volumes:
      - prysm_data:/data
      - ./validator_keys:/config/validator_keys
      - ./passwd/wallet-passwd:/config/wallet-passwd # remember to set your passwd
      - ./passwd/keystore-passwd:/config/keystore-passwd # remember to set your passwd
    env_file:
      - .env

  holesky-prometheus:
    build:
      context: ../../../services/prometheus
      dockerfile: Dockerfile
    container_name: holesky-prometheus
    command: [ "/app/prometheus-entrypoint.sh" ]
    volumes:
      - prometheus_data:/data
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    env_file:
      - .env
