ARG BASE_IMAGE=ubuntu:24.04
ARG ASDF_VERSION=v0.14.1
ARG RUST_VERSION=1.88
ARG REPO=https://github.com/0x00101010/reth.git
ARG COMMIT=982e5dbe97dbb8cb04ddb58b619a2c6267d8d82b

FROM ${BASE_IMAGE} AS builder
WORKDIR /app

# install dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y \
    git \
    libclang-dev \
    pkg-config \
    curl \
    build-essential

# install asdf and rust
ENV ASDF_ROOT=/root/.asdf
ENV PATH="${ASDF_ROOT}/bin:${ASDF_ROOT}/shims:$PATH"
RUN git clone https://github.com/asdf-vm/asdf.git ${ASDF_ROOT} --branch ${ASDF_VERSION}
RUN asdf plugin add rust && \
    asdf install rust ${RUST_VERSION} && \
    asdf global rust ${RUST_VERSION}

# download source code
RUN git init && \
    git remote add origin ${REPO} && \
    git fetch --depth 1 origin ${COMMIT} && \
    git checkout FETCH_HEAD

# build
RUN PROFILE=dev make build-op

FROM ${BASE_IMAGE}
WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    curl \
    jq \
    vim \
    iproute2

COPY --from=builder     /app/target/debug/op-reth   /app/
COPY ./entrypoint.sh                                /app/
