ARG BASE_IMAGE=ubuntu:24.04

FROM ${BASE_IMAGE} AS builder
WORKDIR /app

RUN apt update -y && apt install -y git gpg sudo wget curl apt-utils libclang-dev build-essential
RUN install -dm 755 /etc/apt/keyrings
RUN wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null
RUN echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | tee /etc/apt/sources.list.d/mise.list
RUN apt update
RUN apt install -y mise

ARG RUST_VERSION=1.88
ARG REPO=https://github.com/0x00101010/reth.git
ARG COMMIT=982e5dbe97dbb8cb04ddb58b619a2c6267d8d82b

RUN mise install rust@${RUST_VERSION}
RUN mise use -g rust@${RUST_VERSION}

# download source code
RUN git init && \
    git remote add origin ${REPO} && \
    git fetch --depth 1 origin ${COMMIT} && \
    git checkout FETCH_HEAD

# build
RUN PROFILE=dev make build-op

FROM ${BASE_IMAGE}
WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    curl \
    jq \
    vim \
    iproute2

COPY --from=builder     /app/target/debug/op-reth   /app/
COPY ./entrypoint.sh                                /app/
