ARG BASE_IMAGE=ubuntu:24.04

FROM ${BASE_IMAGE} AS builder
WORKDIR /app

RUN apt update
RUN apt install -y \
    curl \
    git \
    ca-certificates \
    bash \
    build-essential \
    make \
    wget \
    libclang-dev

# install mise (platform/arch auto-detected)
RUN curl -fsSL https://mise.run | sh
ENV PATH="/root/.local/share/mise/shims:/root/.local/bin:${PATH}"
SHELL ["/bin/bash", "-lc"]
RUN eval "$(mise activate bash)"

ARG RUST_VERSION=1.88
ARG REPO=https://github.com/0x00101010/reth.git
ARG COMMIT=982e5dbe97dbb8cb04ddb58b619a2c6267d8d82b

RUN mise install rust@${RUST_VERSION}
RUN mise use -g rust@${RUST_VERSION}

# download source code
RUN git init && \
    git remote add origin ${REPO} && \
    git fetch --depth 1 origin ${COMMIT} && \
    git checkout FETCH_HEAD

# build
RUN PROFILE=dev make build-op

FROM ${BASE_IMAGE}
WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    curl \
    jq \
    vim \
    iproute2

COPY --from=builder     /app/target/debug/op-reth   /app/
COPY ./entrypoint.sh                                /app/
