volumes:
  geth_data:
    name: sepolia_geth_data
  reth_data:
    name: sepolia_reth_data
  lighthouse_data:
    name: sepolia_lighthouse_data
  prysm_data:
    name: sepolia_prysm_data
  prometheus_data:
    name: sepolia_prometheus_data

networks:
  shared_network:
    external: true

services:
  sepolia-el-reth:
    build:
      context: ../../../services/reth
      dockerfile: Dockerfile
    container_name: sepolia-el-reth
    command: [ "/app/reth-entrypoint.sh" ]
    restart: unless-stopped
    volumes:
      - reth_data:/data
      - ./secrets/jwtsecret:/config/jwtsecret
    ports:
      - "${EL_RPC_PORT}:${EL_RPC_PORT}" # json rpc
      - "${EL_WS_PORT}:${EL_WS_PORT}" # ws rpc
      - "${EL_METRICS_PORT}:${EL_METRICS_PORT}" # prometheus at host 7001
      - "${EL_P2P_PORT}:${EL_P2P_PORT}" # p2p
      - "${EL_P2P_PORT}:${EL_P2P_PORT}/udp" # p2p udp
    networks:
      - shared_network
    env_file:
      - .env
  
  sepolia-cl-lighthouse-beacon-node:
    build:
      context: ../../../services/lighthouse
      dockerfile: Dockerfile
    container_name: sepolia-cl-lighthouse-beacon-node
    command: [ "/app/beacon-node-entrypoint.sh" ]
    restart: unless-stopped
    volumes:
      - lighthouse_data:/data
      - ./secrets/jwtsecret:/config/jwtsecret  
    ports:
      - "${BEACON_NODE_METRICS_PORT}:${BEACON_NODE_METRICS_PORT}" # prometheus at host
      - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}" # p2p
      - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}/udp" # p2p
      - "${BEACON_NODE_GRPC_PORT}:${BEACON_NODE_GRPC_PORT}" # grpc gateway port
      - "${BEACON_NODE_RPC_PORT}:${BEACON_NODE_RPC_PORT}" # rpc port
    networks:
      - shared_network
    env_file:
      - .env

  # sepolia-cl-prysm-beacon-node:
  #   build:
  #     context: ../../../services/prysm
  #     dockerfile: Dockerfile
  #   container_name: sepolia-cl-prysm-beacon-node
  #   command: [ "/app/beacon-node-entrypoint.sh" ]
  #   restart: unless-stopped
  #   volumes:
  #     - /data/sepolia/l1/prysm_data:/data
  #     - ./secrets/jwtsecret:/config/jwtsecret
  #   ports:
  #     - "${BEACON_NODE_METRICS_PORT}:${BEACON_NODE_METRICS_PORT}" # prometheus at host
  #     - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}" # p2p
  #     - "${BEACON_NODE_P2P_PORT}:${BEACON_NODE_P2P_PORT}/udp" # p2p
  #     - "${BEACON_NODE_GRPC_PORT}:${BEACON_NODE_GRPC_PORT}" # grpc gateway port
  #     - "${BEACON_NODE_RPC_PORT}:${BEACON_NODE_RPC_PORT}" # rpc port
  #   networks:
  #     - shared_network
  #   env_file:
  #     - .env
    
  sepolia-prometheus:
    build:
      context: ../../../services/prometheus
      dockerfile: Dockerfile
    container_name: sepolia-prometheus
    command: [ "/app/prometheus-entrypoint.sh" ]
    restart: unless-stopped
    volumes:
      - prometheus_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - shared_network
    env_file:
      - .env
