volumes:
  el_data:
  cl_data:
  prometheus_data:

networks:
  shared_network:
    external: true

services:
  el-snapshot-init:
    build:
      context: ../../../services/snapshot-init
      dockerfile: Dockerfile
    command: [ "/app/entrypoint.sh" ]
    container_name: "${EL_DNS}-snapshot-init"
    restart: "no"
    volumes:
      - el_data:/data
    networks:
      - shared_network
    env_file:
      - .env
      - .env.local

  el:
    build:
      context: ../../../services/base-reth-node
      dockerfile: Dockerfile
      args:
        - REPO=${BASE_REPO}
        - COMMIT=${BASE_COMMIT}
        - RUST_VERSION=${RUST_VERSION}
    command: [ "/app/entrypoint.sh" ]
    container_name: "${EL_DNS}"
    restart: unless-stopped
    depends_on:
      el-snapshot-init:
        condition: service_completed_successfully
    volumes:
      - el_data:/data
      - ./secrets/jwtsecret:/config/jwtsecret
    ports:
      - "${EL_RPC_PORT}:${EL_RPC_PORT}" # json rpc
      - "${EL_WS_PORT}:${EL_WS_PORT}" # ws rpc
      - "${EL_METRICS_PORT}:${EL_METRICS_PORT}" # prometheus
      - "${EL_AUTHRPC_PORT}:${EL_AUTHRPC_PORT}"
      - "${EL_P2P_PORT}:${EL_P2P_PORT}"
      - "${EL_P2P_PORT}:${EL_P2P_PORT}/udp"
      - "${EL_DISCOVERY_V5_PORT}:${EL_DISCOVERY_V5_PORT}/udp"
    networks:
      - shared_network
    env_file:
      - .env
      - .env.local

  cl:
    build:
      context: ../../../services/base-consensus
      dockerfile: Dockerfile
      args:
        - REPO=${BASE_REPO}
        - COMMIT=${BASE_COMMIT}
        - RUST_VERSION=${RUST_VERSION}
    command: [ "/app/entrypoint.sh" ]
    container_name: "${CL_DNS}"
    restart: unless-stopped
    depends_on:
      el:
        condition: service_started
    volumes:
      - cl_data:/data
      - ./secrets/jwtsecret:/config/jwtsecret
    ports:
      - "${BASE_NODE_RPC_PORT}:${BASE_NODE_RPC_PORT}"
      - "${BASE_NODE_METRICS_PORT}:${BASE_NODE_METRICS_PORT}"
      - "${BASE_NODE_P2P_LISTEN_TCP_PORT}:${BASE_NODE_P2P_LISTEN_TCP_PORT}"
      - "${BASE_NODE_P2P_LISTEN_UDP_PORT}:${BASE_NODE_P2P_LISTEN_UDP_PORT}/udp"
    networks:
      - shared_network
    env_file:
      - .env
      - .env.local

  prometheus:
    build:
      context: ../../../services/prometheus
      dockerfile: Dockerfile
    container_name: "${PROMETHEUS_DNS}"
    command: [ "/app/prometheus-entrypoint.sh" ]
    restart: unless-stopped
    volumes:
      - prometheus_data:/data
      - ./prometheus-template.yml:/app/prometheus-template.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - shared_network
    env_file:
      - .env
      - .env.local
